scripts/Window-Manager-Setup.sh
Remove comments and unnecessary code for more clean script,
=> Remove unused code & comments 

scripts/Hyprland Setup.sh
Added a Hyprland setup script to install necessary dependencies and configure Hyprland using your github hyprland repository.
=> Hyprland setup script Added

cxfs.sh
This will return back to whipstail for main menu & dialog for submenu.
this is necessary to implement better ui .
=> Menu impl to whipstail & dialog

setup.sh
Refactor the setup.sh script to grab the scripts dir only rather than cloning whole repo. This will increase speed and give performance
Necessary for fast grabbing the scripts.
tested on my local machine.
=> Refactor setup script for speed & reliability

docs/index.md, docs/script.js, docs/style.css
Add JS & CSS script for light and dark theme switcher
Not Tested
=> Docs Light/Dark Mode Switcher

scripts/Install Packages.sh
Adds an option to the installation script to install music-related packages.
=> Add Option to Install Music Packages in Package Script

README.md
As unexpectly reddit badge doesn't seems to work. I will see what happen but for now i am removing it .
=> Remove Reddit Badge From README.md

scripts/Install Packages.sh
Adds Spotify to the music packages, enabling easy installation and integration.
=> Add Spotify to Music Packages

scripts/Install Packages.sh
Added packages: [list of new packages]
- Ranger [Filemanager]
- Nautilus [Filemanager]
- Thorium Broswer [Broswer]
- Kdenlive [Video Editor]
- Keybase [Encrypted Chatting App]
=> Add more essential packages to installation script

.gitignore
Since it is uploaded from the document, there's no need to add it to the repository.
This will help to make repo more clean.
=> Remove Script Zip File 

.github/PULL_REQUEST_TEMPLATE.md
Add New Check Box For Bad Code/Scripts.
Sometime some crappy code may detected. So making a check box for bad code make it more easier to review PR's
=> Pull Request Template 

.github/roadmap.md
=> Update Completed Roadmap Tasks On Carch

scripts/Install Packages.sh
Adds Tor Browser installation option to the `Install Packages` Script .
=> Add Tor Browser Installation into Packages Installation Script

.github/workflows/zip.yml
Path Define To CarchScripts Zip Dir
=> Path Define To CarchScripts Zip Dir

scripts/Dwm Setup.sh, scripts/Hyprland Setup.sh, scripts/Install Fonts.sh, scripts/Install LTS Kernal.sh, scripts/Setup Alacritty.sh, scripts/Setup Aur.sh, scripts/Setup Fastfetch.sh, scripts/Setup GRUB.sh, scripts/Setup Kitty.sh, scripts/Setup Neovim.sh, scripts/Setup Picom.sh, scripts/Setup Rofi.sh, scripts/Setup SDDM.sh, scripts/Setup Themes-Icons.sh, scripts/SwayWM Setup.sh, scripts/Wallpapers.sh, scripts/i3wm Setup.sh
Integrates interactive `gum` menus and confirmation prompts across multiple setup scripts for improved user experience.
This is necessary for simple and clean env for setup script.
=> Add Gum Interactive Menus and Confirmation to Setup Scripts

scripts/Packages.sh
Changes
- Add text editor option in package script.
- Refactoring of script names.
- Add gum navigation in package script.
-  Add paru missing dependencies on package installation script.
Gum in packages installation will help to choose and navigate the menu in proper  way,
https://github.com/user-attachments/assets/41d0b40b-3373-45ba-a37e-47ae9e1430cd
=> Package Installation & Menu Script Refactor

scripts/Packages.sh
The package you have used for Netflix is unofficial so I have put an unofficial tag to make it clear to the user. 
=> Add a tag for netflix unoffical package

cxfs.sh
Hey, a new contributor in town 🥳
Removed the long CXFS heading for a cleaner script and menu.
This change simplifies the script and menu by removing the lengthy CXFS heading, making it cleaner and more focused on the 'Carch' branding.
=> Update CXFS Figlet Heading to Carch

.github/workflows/contributors.yml
Introduces metrics tracking for contributors in Carch to enhance project insights and engagement.
For contributors alignment
=> Add Contributor Metrics to Carch

package.json
Update package build to align with the new Carch structure.
Testing Package
=> Rebase Carch Package Build Structure

scripts/README, scripts/README.txt
Improved README text for clarity and better understanding.
=> Clarify README text for better understanding

package.json
Update `carch` Package To Latest Commit & Structure.
=> Update package to latest structure

scripts/Packages.sh
- Added packages for Android debloat and subsystem support
- Included thumbnail preview and Android USB connection support in the file manager.
Improved overall functionality by enhancing package coverage.
=> Add essential packages to the package script.

.github/PULL_REQUEST_TEMPLATE.md
Improved structure and clarity in the PR template.
=> Refine PR template

README.md
=> Remove discord chat badges from README

README.md
The installation guide has been mentioned in the "Installation" heading of the README. Including it twice in the README is redundant. Users can refer to the detailed installation steps in the `INSTALLATION.md` file.
=> Remove Installation Guide from README

PKGBUILD
Updated the PKGBUILD for the AUR package to ensure compatibility and improve build process
=> Update PKGBUILD for AUR Package

.github/INSTALLATION.md, README.md, docs/index.md
Display the current AUR package version in the `README` `Documentation` `Installation Guide`.
=> Add AUR package version badge to Carch

README.md
Forget to add github logo in `imgshield` badges.
=> Add GitHub logo to README badges

README.md
=>  Update GitHub badge logo color to black

.github/INSTALLATION.md, README.md
The 'Inspiration' tag is already documented in the project's main documentation. As a result, including it in the README is redundant. This PR removes the duplicate mention to streamline the README content.
=> Remove 'Inspiration' tag

PKGBUILD
Update PKGBUILD to change from bin to git package in AUR
=> Change from bin to git package in AUR

carch-gtk.py
This PR adds a `carch-gtk` script to simplify the setup and configuration of GTK-based applications in the Carch setup process.
=> Add carch-gtk Setup Script

.github/ROADMAP.md
=> Add GUI/GTK Check Box Completion

scripts/Packages.sh
Added Yazi file manager support to the package script.
=> Add Yazi File Manager to Package Script

.github/ROADMAP.md, README.md
Updated the roadmap to match Carch's current stage, enhanced the README with more details, fixed known issues, and refined the overall documentation.
=> Refine Roadmap, README, and Documentation

docs/index.html
=> Fix: Mobile Side View on Documentation Website

README.md
=> Enhance README Badges

install/setup.sh
Add GTK installation to setup.
=> Add GTK Installation Support to Setup Script

.github/INSTALLATION.md
=> Refine Installation Guide and Add GTK Setup Instructions

docs/index.html
=> Update docs for latest installation commit

docs/Index/index.md
=> Update Markdown Documentation for Docs

docs/index.html
=> Fix Documentation Headings

gtk/carch-gtk.py
Improves Carch-GTK with script execution notifications, an updated About section, and enhanced interface functionality.
=> Enhance Carch-GTK Interface and Functionality

docs/index.html
=> Add CLI Commands Guide to Documentation

docs/Index/index.md
=> Docs: Update Markdown Documentation

.github/workflows/zip.yml
=> Fix scripts.zip upload workflow

docs/index.html
=> Refine Carch Documentation

README.md
=> Add Discord Invite SVG Badge to README

.github/INSTALLATION.md
=> Simplify Installation Guide

.github/INSTALLATION.md, docs/Index/index.md
=> Document CLI Changes

docs/index.html
=> Add CLI Guide to Documentation

README.md
=> Add a note in readme

docs/installation/aur.md, docs/installation/gtk.md
=> Fix broken image link

docs/.vitepress/config.ts, docs/.vitepress/theme/custom.css, docs/.vitepress/theme/index.ts, docs/acknowledgment/contributors.md, docs/acknowledgment/inspiration.md, docs/github/contributing.md, docs/index.md, docs/installation/aur.md, docs/installation/cli.md, docs/installation/gtk.md, docs/scripts/scripts.md, package.json
- Added CSS for enhanced visual presentation.
- Fixed markdown formatting issues for consistency and readability.
- Introduced new features to enrich the documentation.
=> Refactor Documentation for Improved Visual Appeal

README.md
=> Making readable readme again

docs/get-started.md, docs/getting-started/introduction.md, docs/index.md, docs/installation/aur.md, docs/installation/cli.md, docs/installation/cmd.md, docs/installation/gtk.md
=> Enhance Documentation with Beautiful Updates

.github/PULL_REQUEST_TEMPLATE.md
=> Enhance Pull Request Template

docs/.vitepress/config.ts, docs/.vitepress/theme/custom.css, docs/index.md
=> Refactor Documentation & Some Fixes

docs/index.md
=> Remove Transparency from Top Section

docs/.vitepress/config.ts, docs/getting-started/introduction.md, docs/index.md
=> Enhancement on docs

docs/index.md
=> Fix image width to '150'

CHANGELOG.md
Create the changelog with recent changes, including Old Rust integration and dependency updates.
=> Create Changelog for Carch

CHANGELOG.md
=> Update CHANGELOG.md for v3.0.9

PKGBUILD
=> Update PKGBUILD v3.0.9

docs/.vitepress/config.ts
=> Add Changelog to Top Navigation [Docs]

docs/.vitepress/config.ts
=> Add Carch Version Info [Docs]

CHANGELOG.md
=> Link Changelog to Each Release Tag

gtk/carch-gtk.py
=> Update GTK to v3.0.9

docs/installation/cmd.md
=> Add CarchCLI Installation Guide [Docs]

docs/.vitepress/config.ts, docs/contact.md, docs/index.md
=> Refinements to Documentation

scripts/Packages.sh
=> Add terminal installation to packages script

build/core.sh
=> Remove last script tracking from core

PKGBUILD
=> SHA256 Checksum Verification Passed

docs/installation/cli.md
=> Update: Enhance CLI Installation Tip Section

docs/about.md
=> Remove Unused 'aboutinfo' Markdown from [docs]

README.md
=> Add Penguin Img Src

docs/.vitepress/config.ts
=> Update to GPL 3.0 License [Docs]

docs/installation/aur.md
=> Fix and Update AUR Package Build [ docs ]

README.md
=> Update Transferd Documentation Link in README

install/setup.sh
=> Fix Script Detection and Bugs

scripts/Packages.sh
=> Add Gum Spin [Packages Script]

scripts/Hyprland.sh
=> Add Gum Spin To `Hyprland` Script

build/carch
=> Bump `v3.0.9` To `v4.0.0`

CHANGELOG.md
=> CHANGELOG From `v3.0.9` To `v4.0.0`

scripts/Sddm.sh
=> Fix `SDDM` Theme Dir  [Scripts]

CHANGELOG.md
=> Add [Note] Carch v4.0.0 `CHANGELOG`

install/run.sh, install/setup.sh
=> Fix Carch `Installation` ⛓️

scripts/Packages.sh
=> Fix Gum Bug 🐛 [Package Script]

build/carch
=> Add Returing To Menu [Back]

build/carch
=> Include `GTK` & `CLI` [Main Script]

gtk/carch-gtk.py
=> Fix Script [DIR]

install/setup.sh
=> Remove CLI/GTK As Include [Main Script]

install/setup.sh
=> Refactor Setup Script

install/run.sh, install/setup.sh
=> Refactor Installation Script

scripts/Alacritty.sh, scripts/Aur.sh, scripts/Dwm.sh, scripts/Fastfetch.sh, scripts/Fonts.sh, scripts/Grub.sh, scripts/Hyprland.sh, scripts/Kitty.sh, scripts/LTS-Kernal.sh, scripts/Neovim.sh, scripts/Packages.sh, scripts/Picom.sh, scripts/Rofi.sh, scripts/Sddm.sh, scripts/SwayWM.sh, scripts/Themes-Icons.sh, scripts/Wallpapers.sh, scripts/i3wm.sh
=> Refactor Whole Scripts [Carch]

man/carch.1
=> man-page for [Carch] 📄

install/run.sh, install/setup.sh
=> Update Script for Man Pages Handling

build/carch, gtk/carch-gtk.py, install/setup.sh
=> Bump Version 4.1.0

CHANGELOG.md
=> 4.1.0 CHANGELOG

CHANGELOG.md
=> Add AUR Update Note [CHANGELOG v4.1.0]

build/carch
=> Add [Logging] Carch

gtk/carch-gtk.py
=> Add logging `Carch` [GTK]

install/run.sh
=> Making Script Clean 🧹

install/setup.sh
=> Making Setup Installation `clean` 🧹

.github/workflows/zip.yml, scripts/Alacritty.sh, scripts/Aur.sh, scripts/Dwm.sh, scripts/Fonts.sh, scripts/Hyprland.sh, scripts/Neovim.sh, scripts/Picom.sh, scripts/Sddm.sh, scripts/SwayWM.sh, scripts/i3wm.sh
=> Script Fixes [BUG]

carch.desktop
=> Add Carch Icons [Desktop Entry]

install/setup.sh
=> Added Icon For Desktop Entry

build/carch
=> Add Uninstall Command [Carch]

scripts/Packages.sh
=> Add Some Packages [Package Script]

build/carch
=> Added Useful Command [Carch --[options]]

config/carch.conf
=> Config File Example

completions/bash/carch, completions/zsh/_carch
=> Auto Completions [`Bash` `Zsh`]

completions/fish/carch.fish
=> Fish Completions [Added]

install/setup.sh
- [z] Updates 
- [z] Feature 
- [z] UI/UX
=> Added Commands Completions [ZSH BASH FISH]

build/carch
=> Add Completions To Uninstall [Command]

build/carch, gtk/carch-gtk.py, install/setup.sh, man/carch.1
=> Upgrade Version 4.1.1

build/carch, install/setup.sh
=> Fix Completions Removel

build/carch, install/setup.sh
=> Minor Fish Dir Fixes

tui/src/floating_text.rs, tui/src/hint.rs, tui/src/state.rs
=> Fix With Cargo Clippy & Cargo FMT [RUST]

install/tui.sh
=> Setup Script For TUI

.github/workflows/rust-build.yml, build/carch, completions/bash/carch, completions/fish/carch.fish, completions/zsh/_carch, install/setup.sh
=> Tui Installation On Progress

core/tabs/applications-setup/tab_data.toml, core/tabs/applications-setup/tmux.sh, scripts/tmux.sh
=> Added Tmux Setup Script

core/tabs/system-setup/sddm.sh, scripts/Sddm.sh
=> Add autologin in sddm [Autologin INFO]

install/run.sh, install/setup.sh, install/tui.sh
=> Refactor Setup Script [ New Design ]

Cargo.lock, Cargo.toml, build/carch, core/Cargo.toml, install/setup.sh, man/carch.1, tui/Cargo.toml
=> Bump Version 4.1.2

install/run.sh, install/setup.sh, install/tui.sh
=> Revert "Refactor Setup Script [ New Design ]"

scripts/Fonts.sh
This pull request adds/updates/fixes [describe the main goal or feature].
=> Fix Formatting With SHFMT

scripts/Fonts.sh
=> Permission Issue [ Maybe Fixed ] Test

Cargo.lock, tui/Cargo.toml
=> Revert "Bump tree-sitter-highlight from 0.24.6 to 0.25.1"

core/tabs/applications-setup/alacritty.sh, core/tabs/applications-setup/fastfetch.sh, core/tabs/system-setup/aur.sh, scripts/Alacritty.sh, scripts/Aur.sh, scripts/Bash.sh, scripts/Dwm.sh, scripts/Fastfetch.sh, scripts/Fish.sh, scripts/Fonts.sh, scripts/Grub.sh, scripts/Helix.sh, scripts/Hyprland.sh, scripts/Kitty.sh, scripts/LTS-Kernel.sh, scripts/Neovim.sh, scripts/Packages.sh, scripts/Picom.sh, scripts/Rofi.sh, scripts/Sddm.sh, scripts/SwayWM.sh, scripts/Themes-Icons.sh, scripts/Tmux.sh, scripts/Zsh.sh, scripts/i3wm.sh
This pull request adds/updates/fixes [describe the main goal or feature].
=> Initial Support For Fedora Linux

README.md
=> Remove Rust

completions/bash/carch, completions/fish/carch.fish, completions/zsh/_carch
=> Remove Rust Stuffs From [ Completions ]

scripts/i3wm.sh
=> Add Kitty As Terminal Dependencies

install/arch-setup.sh, install/fedora-setup.sh
=> Fix Installation Script `Arch` & `Fedora`

scripts/Aur.sh, scripts/Bash.sh, scripts/Dwm.sh, scripts/Hyprland.sh, scripts/Neovim.sh, scripts/Packages.sh, scripts/Rofi.sh, scripts/Zsh.sh, scripts/i3wm.sh
=> Fix Detection of OS-Release [ Arch & Fedora ]

scripts/Bun.sh, scripts/Npm.sh
=> Add Npm & Bun Installation Script

scripts/Zsh.sh
=> Fix Zsh Installation [ Arch * Fedora ]

scripts/Dwm.sh, scripts/Fish.sh, scripts/Helix.sh, scripts/Hyprland.sh, scripts/Picom.sh, scripts/Sddm.sh
=> Fix Major Os Detection [ Arch * Fedora ] Based

scripts/i3wm.sh
=> Fix i3wm setup script [ From i3wmdotfiles ]

build/carch, carch.desktop, install/arch-setup.sh, install/fedora-setup.sh, man/carch.1
=> Bump Version 4.1.4

scripts/Npm.sh
=> Fix Npm Script Fail On Both Distro

.github/workflows/release.yml
=> Fix Img Shield Badges Tag Output [ Release ]

Cargo.toml
=> Prepare for Carch Crate Release

install/arch-setup.sh, install/fedora-setup.sh, man/carch.1, src/scripts/carch
=> Bump Version 4.1.5

src/scripts/scripts/Neovim.sh
=> Fix Neovim Script Not Working

src/scripts/scripts/Aur.sh, src/scripts/scripts/Bash.sh, src/scripts/scripts/Dwm.sh, src/scripts/scripts/Fastfetch.sh, src/scripts/scripts/Fish.sh, src/scripts/scripts/Helix.sh, src/scripts/scripts/Neovim.sh, src/scripts/scripts/Npm.sh, src/scripts/scripts/Zsh.sh
=> Fix Major Bugs & Dependencies

src/scripts/scripts/Dwm.sh, src/scripts/scripts/Fonts.sh
=> Dependencies Fulfill [ Dwm ]

src/scripts/scripts/Chaotic-Aur.sh
=> Add Chaotic Aur Installation Script

src/scripts/scripts/Packages.sh
=> Fixes & Add More Packages [ Package Script ]

Cargo.lock, Cargo.toml, install/arch-setup.sh, install/fedora-setup.sh, man/carch.1, src/main.rs, src/scripts/carch
=> Bump Version 4.1.6

src/scripts/carch
=> Add Carch Update Check Command

completions/bash/carch, completions/fish/carch.fish, completions/zsh/_carch, src/scripts/carch
=> feat: Added Carch Search

src/scripts/scripts/Packages.sh
=> Fix Qemu Installation

src/scripts/carch
=> Cleaning Uninstall Carch Function [ Fedora ]

live.sh
This can be necessary to test Carch live, such as downloading it to a temporary file and running it. If you like, you can install it, but you can also use it temporarily.
=> Creating Live Testing [ Carch ]

Cargo.lock, Cargo.toml, arch/install.sh, fedora/carch.spec, fedora/install.sh, man/carch.1, src/scripts/carch
=> Bump Version 4.1.7

arch/install.sh
=> Remove Carch-Bin

.github/workflows/release.yml
=> Change To Manual Tagging [ Release ]

src/scripts/scripts/Sddm.sh
=> Fix Minor Bug [ SDDM ]

src/scripts/carch
=> Remove Carch Bin

Cargo.toml, arch/install.sh, fedora/carch.spec, fedora/install.sh, man/carch.1
=> Bump Version 4.2.1

src/scripts/carch
=> Changing Gum menu style to FZF style

src/scripts/carch
=> Fix Version Logic [ Commands ]

src/scripts/carch
=> Fix Versioning

src/scripts/scripts/Aur.sh, src/scripts/scripts/Bash.sh, src/scripts/scripts/Bun.sh, src/scripts/scripts/Chaotic-Aur.sh, src/scripts/scripts/Dwm.sh, src/scripts/scripts/Fish.sh, src/scripts/scripts/Helix.sh, src/scripts/scripts/LTS-Kernel.sh, src/scripts/scripts/Npm.sh, src/scripts/scripts/Packages.sh, src/scripts/scripts/Picom.sh, src/scripts/scripts/Sddm.sh, src/scripts/scripts/Wallpapers.sh, src/scripts/scripts/Zsh.sh, src/scripts/scripts/i3wm.sh
Check Discussions https://github.com/harilvfs/carch/discussions/320
=> Minimizing Gum Stuffs [ Scripts ]

src/main.rs
=> Rust Code Makeover & Added Comments

live.sh
=> Some Enhancement Check UP

src/scripts/scripts/Dunst.sh
=> feat: Add Dunst Setup Script

live.sh, src/scripts/scripts/Alacritty.sh, src/scripts/scripts/Fastfetch.sh, src/scripts/scripts/Fonts.sh, src/scripts/scripts/Grub.sh, src/scripts/scripts/Hyprland.sh, src/scripts/scripts/Kitty.sh, src/scripts/scripts/LTS-Kernel.sh, src/scripts/scripts/Neovim.sh, src/scripts/scripts/Picom.sh, src/scripts/scripts/Rofi.sh, src/scripts/scripts/Sddm.sh, src/scripts/scripts/SwayWM.sh, src/scripts/scripts/Themes-Icons.sh, src/scripts/scripts/Tmux.sh, src/scripts/scripts/Wallpapers.sh, src/scripts/scripts/i3wm.sh
=> refactor: Completely Remove Gum From Scripts

src/scripts/scripts/SwayWM.sh
=> fix: AUR helper Swaywm

arch/install.sh, fedora/install.sh, updater.sh
=> refactor: Rework On Install Script

src/scripts/scripts/Alacritty.sh, src/scripts/scripts/Aur.sh, src/scripts/scripts/Bash.sh, src/scripts/scripts/Bun.sh, src/scripts/scripts/Chaotic-Aur.sh, src/scripts/scripts/Dwm.sh, src/scripts/scripts/Fastfetch.sh, src/scripts/scripts/Fish.sh, src/scripts/scripts/Fonts.sh, src/scripts/scripts/Grub.sh, src/scripts/scripts/Helix.sh, src/scripts/scripts/Hyprland.sh, src/scripts/scripts/Kitty.sh, src/scripts/scripts/LTS-Kernel.sh, src/scripts/scripts/Neovim.sh, src/scripts/scripts/Npm.sh, src/scripts/scripts/Packages.sh, src/scripts/scripts/Picom.sh, src/scripts/scripts/Rofi.sh, src/scripts/scripts/Sddm.sh, src/scripts/scripts/SwayWM.sh, src/scripts/scripts/Themes-Icons.sh, src/scripts/scripts/Tmux.sh, src/scripts/scripts/Wallpapers.sh, src/scripts/scripts/Zsh.sh, src/scripts/scripts/i3wm.sh
=> fix: Simplify Distro Detection Logic

src/scripts/scripts/Dwm.sh
=> feat: Added support for using DWM from TTY

src/scripts/modules/system/Fonts.sh
=> chore: Clean up [ Font Script ]

src/scripts/carch
=> refactor: Rework banner and improve fzf menu

src/scripts/modules/desktop/Dunst.sh, src/scripts/modules/desktop/Dwm.sh, src/scripts/modules/desktop/Hyprland.sh, src/scripts/modules/desktop/Picom.sh, src/scripts/modules/desktop/Rofi.sh, src/scripts/modules/desktop/SwayWM.sh, src/scripts/modules/desktop/Themes-Icons.sh, src/scripts/modules/desktop/Wallpapers.sh, src/scripts/modules/desktop/i3wm.sh, src/scripts/modules/development/Bun.sh, src/scripts/modules/development/Helix.sh, src/scripts/modules/development/Neovim.sh, src/scripts/modules/development/Npm.sh, src/scripts/modules/system/Aur.sh, src/scripts/modules/system/Chaotic-Aur.sh, src/scripts/modules/system/Fastfetch.sh, src/scripts/modules/system/Fonts.sh, src/scripts/modules/system/Grub.sh, src/scripts/modules/system/LTS-Kernel.sh, src/scripts/modules/system/Packages.sh, src/scripts/modules/system/Sddm.sh, src/scripts/modules/terminal/Alacritty.sh, src/scripts/modules/terminal/Bash.sh, src/scripts/modules/terminal/Fish.sh, src/scripts/modules/terminal/Kitty.sh, src/scripts/modules/terminal/Tmux.sh, src/scripts/modules/terminal/Zsh.sh
=> docs: Add Description to scripts

src/scripts/carch
This change improves performance.  
=> refactor: Redoing the Main Menu

platforms/arch/install.sh, platforms/fedora/install.sh
=> fix: Updates to Carch installer for Arch & Fedora

platforms/fedora/build.sh, platforms/fedora/install.sh
=> refactor: Install Fedora RPMs directly

.github/workflows/release.yml, .github/workflows/rpm-build.yml
=> ci: RPM Builder For Carch [ Fedora ]

completions/bash/carch, completions/fish/carch.fish, completions/zsh/_carch, config/carch.conf
=> update: Commands now compatible with new options

src/scripts/carch
=> remove: Removing Version Text From Menu

src/scripts/carch
=> update: Simplifying the banner

src/main.rs
=> perf: Reduce Rust code and improve performance

src/scripts/carch
=> custom: Simplifying hardcoded parts

src/scripts/carch
=> perf: Pre-populating Script

src/scripts/carch
=> chore: Update Dependencies Handling

src/scripts/modules/desktop/i3wm.sh
=> fix: My Nonsense Mistake

src/scripts/modules/desktop/SwayWM.sh
=> fix: Once Again My Mistake

src/scripts/modules/terminal/Kitty.sh
=> update: Added Tab Config

src/main.rs, src/scripts/carch
=> build: Migrate --help info in Rust

Cargo.lock, Cargo.toml, src/main.rs, typos.toml
=> rust: Creating a TUI to Display Help Info

src/scripts/carch
=> update: Clean Up After Running Script

src/display.rs, src/scripts/carch
=> remove: Cleanup Script that is not needed in carch

src/ui.rs
=> ui: Improve Heading & Add Help Info

src/ui.rs
=> feat: Added Confirmation Before Running Scripts

src/modules/desktop/Dunst.sh, src/modules/desktop/Dwm.sh, src/modules/desktop/Hyprland.sh, src/modules/desktop/Rofi.sh, src/modules/desktop/SwayWM.sh, src/modules/desktop/Wallpapers.sh, src/modules/desktop/i3wm.sh, src/modules/development/Bun.sh, src/modules/development/Helix.sh, src/modules/system/Chaotic-Aur.sh, src/modules/system/Fastfetch.sh, src/modules/system/Fonts.sh, src/modules/system/Grub.sh, src/modules/system/LTS-Kernel.sh, src/modules/system/Sddm.sh, src/modules/terminal/Alacritty.sh, src/modules/terminal/Fish.sh, src/modules/terminal/Kitty.sh, src/modules/terminal/Tmux.sh, src/modules/terminal/Zsh.sh
removing fzf confirmation as we are using confirm in main menu tui.
=> remove: fzf confirmation

src/modules/desktop/Dunst.sh, src/modules/desktop/Dwm.sh, src/modules/desktop/Hyprland.sh, src/modules/desktop/Picom.sh, src/modules/desktop/Rofi.sh, src/modules/desktop/SwayWM.sh, src/modules/desktop/Themes-Icons.sh, src/modules/desktop/Wallpapers.sh, src/modules/desktop/i3wm.sh, src/modules/development/Bun.sh, src/modules/development/Helix.sh, src/modules/development/Neovim.sh, src/modules/development/Npm.sh, src/modules/system/Aur.sh, src/modules/system/Chaotic-Aur.sh, src/modules/system/Fastfetch.sh, src/modules/system/Fonts.sh, src/modules/system/Grub.sh, src/modules/system/LTS-Kernel.sh, src/modules/system/Packages.sh, src/modules/system/Sddm.sh, src/modules/terminal/Alacritty.sh, src/modules/terminal/Bash.sh, src/modules/terminal/Fish.sh, src/modules/terminal/Kitty.sh, src/modules/terminal/Tmux.sh, src/modules/terminal/Zsh.sh
=> UI/UX: Improve fzf menu style

platforms/arch/install.sh, platforms/fedora/build.sh, platforms/fedora/carch.spec, platforms/fedora/install.sh
=> refactor: Cleanup & Simplified Install Script

platforms/src/main.rs
=> bug: fix install script

src/ui.rs
=> feat: Added Multi Select

src/commands.rs, src/display.rs, src/main.rs, src/script_list.rs
=> update: make command to support cargo

src/modules/terminal/Foot.sh, src/modules/terminal/Ghostty.sh
=> feat: Added foot & ghostty setup script

Cargo.lock, Cargo.toml, src/display.rs, src/script_list.rs, src/ui.rs
=> rust: changes adapt from ratatui v29

CHANGELOG.md
PR to update the CHANGELOG.md with the latest changes for version v4.4.3.
```markdown
* Changelog v4.4.2 by @harilvfs in https://github.com/harilvfs/carch/pull/435
* Update Cargo.lock [`6adfa8f`](https://github.com/harilvfs/carch/commit/6adfa8f)
* Update message.yml [`3087c4e`](https://github.com/harilvfs/carch/commit/3087c4e)
* Update message.yml [`38a4f1d`](https://github.com/harilvfs/carch/commit/38a4f1d)
* Update message.yml [`4f37f62`](https://github.com/harilvfs/carch/commit/4f37f62)
* Update message.yml [`9c1c07c`](https://github.com/harilvfs/carch/commit/9c1c07c)
* Update message.yml [`a876239`](https://github.com/harilvfs/carch/commit/a876239)
* Update version to 4.4.3 for release [`2a88b8a`](https://github.com/harilvfs/carch/commit/2a88b8a)
* Update version to 4.4.3 for release …
```
=> Changelog v4.4.3

CHANGELOG.md
PR to update the CHANGELOG.md with the latest changes for version v4.4.5.
```markdown
* Changelog v4.4.4 by @harilvfs in https://github.com/harilvfs/carch/pull/441
* Update README.md [`41e0651`](https://github.com/harilvfs/carch/commit/41e0651)
* Update README.md [`4911ff3`](https://github.com/harilvfs/carch/commit/4911ff3)
* Update README.md [`4a4df08`](https://github.com/harilvfs/carch/commit/4a4df08)
* Update README.md [`4b02b5d`](https://github.com/harilvfs/carch/commit/4b02b5d)
* Update README.md [`589f9f6`](https://github.com/harilvfs/carch/commit/589f9f6)
* Update README.md [`7543812`](https://github.com/harilvfs/carch/commit/7543812)
* Update README.md [`d0b812b`](https://github.com/harilvfs/carch/commit/d0b812b)
* Update README.md …
```
=> Changelog v4.4.5

CHANGELOG.md
PR to update the CHANGELOG.md with the latest changes for version v4.4.7.
```markdown
* Changelog v4.4.6 [`e650f9d`](https://github.com/harilvfs/carch/commit/e650f9d)
* Changelog v4.4.6 by @harilvfs in https://github.com/harilvfs/carch/pull/450
* Update README.hi.md [`ee6c6e8`](https://github.com/harilvfs/carch/commit/ee6c6e8)
* Update README.md [`189d7c7`](https://github.com/harilvfs/carch/commit/189d7c7)
* Update README.md [`2ebb5bc`](https://github.com/harilvfs/carch/commit/2ebb5bc)
* Update README.np.md [`467e6a8`](https://github.com/harilvfs/carch/commit/467e6a8)
* Update version to 4.4.7 for release [`f4b2ed6`](https://github.com/harilvfs/carch/commit/f4b2ed6)
* a [`177d0fd`](https://github.com/harilvfs/carch/commit/177d0fd)
* chore(deps): add missing azote pkg [swaywm script] …
```
=> Changelog v4.4.7

src/modules/Terminal/Bash.sh, src/modules/Terminal/Zsh.sh
i am adding an optional option in case the user wants to set the default shell to zsh or bash.
=> feat: add defaulting option to [ zsh bash ] scripts

src/display.rs, src/script_list.rs
=> rust: rounded script list & help [ ui ]

CHANGELOG.md
=> changelog for v5.1.1

.github/README.md
=> docs(style): remove using of bold text's

scripts/cleanup.sh
=> chore(script): remove comments

Cargo.toml, carch.desktop, man/carch.1, scripts/install.sh
=> chore: update project description

CHANGELOG.md
=> changelog for v5.1.2

.github/README.md
=> docs(readme): add preview

.gitignore, scripts/install/Makefile, scripts/install/go.mod, scripts/install/go.sum, scripts/install/install.go, scripts/install/main.go, scripts/install/uninstall.go, scripts/install/update.go, scripts/install/utils.go
as from starting of carch i guess i have only written the install script in rust (tui). i find bash as superior for kind of install script and all. but due to kind of more robust handling of logic and many things i want to write this in nim but i failed as fucking i don't know nim lang. so i finally decided to write this in go lang. it is kinda perfect clean and better for maintainability. and it works fine i am on initial all done. remaining is ci and other thing i have to test that first and we are good to go i guess.
https://github.com/user-attachments/assets/eb9afb9e-c7f2-4ad5-9ada-213677528b98
=> feat(installer): rewrite install script in Go

CHANGELOG.md
=> changelog for v5.1.4

CHANGELOG.md
=> changelog for v5.1.5

CHANGELOG.md
=> changelog for v5.1.6

src/ui/app.rs, src/ui/popups.rs, src/ui/render.rs
the tui has been redesigned.
- we now have separate sections for categories and scripts.  
- we can switch between them using the h and l keyboard shortcuts.
https://github.com/user-attachments/assets/a0f34a13-5d22-4aed-824d-7e8ddb09bffd
=> refactor(ui): new tui design

.github/README.md
=> docs(readme): add quick test guide

CHANGELOG.md
=> changelog for v5.2.1

CHANGELOG.md
=> changelog for v5.2.2

src/args.rs, src/commands.rs, src/error.rs, src/main.rs, src/ui/actions.rs, src/ui/app.rs, src/ui/events.rs, src/ui/popups/confirmation.rs, src/ui/popups/help.rs, src/ui/popups/preview.rs, src/ui/popups/run_script.rs, src/ui/popups/search.rs, src/ui/render.rs, src/ui/state.rs, src/ui/system_info.rs, src/ui/widgets/category_list.rs, src/ui/widgets/header.rs, src/ui/widgets/script_list.rs, src/ui/widgets/status_bar.rs, src/version.rs
check https://github.com/harilvfs/carch/issues/535
Address #535
=> refactor: document rust code

CHANGELOG.md
=> changelog for v5.2.5

CHANGELOG.md
=> changelog for v5.2.6

scripts/modules/Desktop/Dunst.sh, scripts/modules/Desktop/Wallpapers.sh, scripts/modules/Development/Npm.sh, scripts/modules/Packages/Android-Tools.sh, scripts/modules/Packages/Browsers.sh, scripts/modules/Packages/Communication.sh, scripts/modules/Packages/Crypto-Tools.sh, scripts/modules/Packages/Development-Tools.sh, scripts/modules/Packages/Editing.sh, scripts/modules/Packages/FM-Tools.sh, scripts/modules/Packages/FileManagers.sh, scripts/modules/Packages/Gaming.sh, scripts/modules/Packages/GitHub.sh, scripts/modules/Packages/Multimedia.sh, scripts/modules/Packages/Music.sh, scripts/modules/Packages/Productivity.sh, scripts/modules/Packages/Streaming.sh, scripts/modules/Packages/Terminals.sh, scripts/modules/Packages/TextEditors.sh, scripts/modules/Packages/Virtualization.sh, scripts/modules/System/Grub.sh, scripts/modules/Terminal/Bash.sh, scripts/modules/Terminal/Fish.sh, scripts/modules/Terminal/Kitty.sh, scripts/modules/Terminal/Tmux.sh, scripts/modules/Terminal/Zsh.sh
just making the scripts more better by defining functions and calling them.
=> refactor(scripts): using function call

CHANGELOG.md
=> changelog for v5.2.7

.github/README.md
See: https://github.com/ratatui/ratatui/pull/2040 & https://github.com/ratatui/ratatui-website/pull/924
Do not delete this section. Please ensure your pull request meets the following requirements:
=> docs(readme): use mainstream ImgShield Ratatui badge

.github/README.md
Do not delete this section. Please ensure your pull request meets the following requirements:
=> docs(readme): use same style badge as Ratatui

CHANGELOG.md
=> changelog for v5.3.1
